# EU868 region configuration (based on ChirpStack example)
[[regions]]
  # Name is a user-defined identifier for this region.
  name="eu868"

  # Common-name refers to the common-name of this region as defined by
  # the LoRa Alliance.
  common_name="EU868"

  # Gateway configuration.
  [regions.gateway]
    force_gws_private=false

    # Gateway backend configuration.
    [regions.gateway.backend]
      enabled="mqtt"

      [regions.gateway.backend.mqtt]
        event_topic="eu868/gateway/+/event/+"
        command_topic="eu868/gateway/{{ gateway_id }}/command/{{ command }}"
        server="tcp://mosquitto:1883"
        username=""
        password=""
        qos=0
        clean_session=true
        client_id=""
        ca_cert=""
        tls_cert=""
        tls_key=""

    # Gateway channels (standard EU868 set)
    [[regions.gateway.channels]]
      frequency=868100000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=868300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=868500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=867100000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=867300000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=867500000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=867700000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=867900000
      bandwidth=125000
      modulation="LORA"
      spreading_factors=[7, 8, 9, 10, 11, 12]

    [[regions.gateway.channels]]
      frequency=868300000
      bandwidth=250000
      modulation="LORA"
      spreading_factors=[7]

    [[regions.gateway.channels]]
      frequency=868800000
      bandwidth=125000
      modulation="FSK"
      datarate=50000

  # Region specific network configuration.
  [regions.network]
    installation_margin=10
    rx_window=0
    rx1_delay=1
    rx1_dr_offset=0
    rx2_dr=0
    rx2_frequency=869525000
    rx2_prefer_on_rx1_dr_lt=0
    rx2_prefer_on_link_budget=false
    downlink_tx_power=-1
    adr_disabled=false
    min_dr=0
    max_dr=5

    [regions.network.rejoin_request]
      enabled=false
      max_count_n=0
      max_time_n=0

    [regions.network.class_b]
      ping_slot_dr=0
      ping_slot_frequency=0

    # Extra channels (EU868)
    [[regions.network.extra_channels]]
      frequency=867100000
      min_dr=0
      max_dr=5

    [[regions.network.extra_channels]]
      frequency=867300000
      min_dr=0
      max_dr=5

    [[regions.network.extra_channels]]
      frequency=867500000
      min_dr=0
      max_dr=5

    [[regions.network.extra_channels]]
      frequency=867700000
      min_dr=0
      max_dr=5

    [[regions.network.extra_channels]]
      frequency=867900000
      min_dr=0
      max_dr=5
